module.exports = {
	get: function (is_admin) {
		return [[
			//{ foucs: false, class1: "", c2: "recharge_diamond", href: "/admin/recharge/view/diamond", name: "赠送钻石" },
			{ foucs: false, class1: "", c2: "tb_alliance_jiangchi", href: "/admin/tb_alliance_jiangchi/view/search", name: "奖池设置" },
			{ foucs: false, class1: "", c2: "tb_users_gps", href: "/admin/tb_users/gps", name: "GPS设置" },
			// { foucs: false, class1: "", c2: "tb_addjifenreq", href: "/admin/tb_addjifenreq/view/list", name: "tb_addjifenreq" },
			// { foucs: false, class1: "", c2: "tb_alliance", href: "/admin/tb_alliance/view/list", name: "tb_alliance" },
			// { foucs: false, class1: "", c2: "tb_alliance_club", href: "/admin/tb_alliance_club/view/list", name: "tb_alliance_club" },
			// { foucs: false, class1: "", c2: "tb_clubmsgs", href: "/admin/tb_clubmsgs/view/list", name: "tb_clubmsgs" },
			// { foucs: false, class1: "", c2: "tb_joinmessage", href: "/admin/tb_joinmessage/view/list", name: "tb_joinmessage" },
			// { foucs: false, class1: "", c2: "tb_monthplaytimes", href: "/admin/tb_monthplaytimes/view/list", name: "tb_monthplaytimes" },
			// { foucs: false, class1: "", c2: "tb_myzj_logs", href: "/admin/tb_myzj_logs/view/list", name: "tb_myzj_logs" },
			// { foucs: false, class1: "", c2: "tb_online_logs", href: "/admin/tb_online_logs/view/list", name: "tb_online_logs" },
			// { foucs: false, class1: "", c2: "tb_paijuhuigu_logs", href: "/admin/tb_paijuhuigu_logs/view/list", name: "tb_paijuhuigu_logs" },
			// { foucs: false, class1: "", c2: "tb_joinclubs", href: "/admin/tb_joinclubs/view/list", name: "tb_joinclubs" },
			// { foucs: false, class1: "", c2: "tb_clubs", href: "/admin/tb_clubs/view/list", name: "tb_clubs" },
			// { foucs: false, class1: "", c2: "tb_dairu_logs", href: "/admin/tb_dairu_logs/view/list", name: "tb_dairu_logs" },
			// { foucs: false, class1: "", c2: "tb_roommessage", href: "/admin/tb_roommessage/view/list", name: "tb_roommessage" },
			// { foucs: false, class1: "", c2: "tb_rooms", href: "/admin/tb_rooms/view/list", name: "tb_rooms" },
			// { foucs: false, class1: "", c2: "tb_sysnotice", href: "/admin/tb_sysnotice/view/list", name: "tb_sysnotice" },
			// { foucs: false, class1: "", c2: "tb_usermemo", href: "/admin/tb_usermemo/view/list", name: "tb_usermemo" },
			// { foucs: false, class1: "", c2: "tb_usermessage", href: "/admin/tb_usermessage/view/list", name: "tb_usermessage" },
			// { foucs: false, class1: "", c2: "tb_issue_logs", href: "/admin/tb_issue_logs/view/list", name: "tb_issue_logs" },
			// { foucs: false, class1: "", c2: "tb_users", href: "/admin/tb_users/view/list", name: "tb_users" },
			// { foucs: false, class1: "", c2: "tb_game_logs", href: "/admin/tb_game_logs/view/list", name: "tb_game_logs" },
			// { foucs: false, class1: "", c2: "tb_issue", href: "/admin/tb_issue/view/list", name: "tb_issue" },
			// { foucs: false, class1: "", c2: "tb_game", href: "/admin/tb_game/view/list", name: "tb_game" },
			// { foucs: false, class1: "", c2: "tb_clubjjalertmessage", href: "/admin/tb_clubjjalertmessage/view/list", name: "tb_clubjjalertmessage" },
			// { foucs: false, class1: "", c2: "tb_mymessage", href: "/admin/tb_mymessage/view/list", name: "tb_mymessage" },
			// { foucs: false, class1: "", c2: "tb_roomlogs", href: "/admin/tb_roomlogs/view/list", name: "tb_roomlogs" },
			// { foucs: false, class1: "", c2: "tb_alliance_jiangchi", href: "/admin/tb_alliance_jiangchi/view/list", name: "tb_alliance_jiangchi" },
			// { foucs: false, class1: "", c2: "tb_dairu", href: "/admin/tb_dairu/view/list", name: "tb_dairu" },
			// { foucs: false, class1: "", c2: "tb_userjifen_info", href: "/admin/tb_userjifen_info/view/list", name: "tb_userjifen_info" },
		]];
	}
}